oceanobservatories/stream_engine

model/preload.py
There was an issure where numbers were encoded in the function map. When this code tried to apply the startsWith method to those values it failed the entire request. This change remedies that by checking if the value is a string first.
=> fix for an issue with processing the function map

.gitmodules, config.py, test/unit_test.py
I have installed ion-functions into the pre-packaged python and it seems to work correctly.  I updated the wiki page with the new instructions.
=> remove ion-functions submodule in favor of manual install

RELEASE_NOTES, util/datamodel.py, util/stream_dataset.py
Change-Id: I9d7f68722087d4b96af4501f7b8ee6751cdc510b
=> Issue #12238 Don't drop duplicate timestamps from separate deployments

manage-streamng
Removing "source activate engine" so users who need to run this script can utilize their own Conda environment that may be named something other than "engine".
=> Issue #12501

RELEASE_NOTES.md, util/annotation.py
- allow open ended annotations to be correctly deserialized, but
prevent them from being used as other logic hasn't been updated
to handle endDT values of None
- update RELEASE_NOTES file format in preparation for possibly
hooking it into versions service
- fix incorrectly placed issue in RELEASE_NOTES
=> Issue #11444 Prevent crash on open ended annotations

RELEASE_NOTES.md, gunicorn_config.py, run.py
Has been tested on uframe-3-test allowing plotting of a zplsc echogram through loading of preload from postgres.
=> Issue #12515 Use preload data from postgres

RELEASE_NOTES.md, manage-streamng
Tested this on uframe-3-test yesterday by starting stream_engine running "manage_streamng start" from the miniconda2 folder within the anaconda environment. I ran a request provided from Seth that triggered an aggregation. I verified within the logs that no exception occurred and that a file named status.txt containing "complete" was generated within a new folder inside /opt/ooi/async/seth on that server.
=> Issue #12916 Enable starting stream_engine from any folder

util/stream_dataset.py
This fix will filter out any data that does not have a corresponding deployment in asset management.
=> Issue #12879 Exclude data without a deployment

RELEASE_NOTES.md, engine/routes.py
NetCDF status and failure file naming conventions used start and end times in their filenames, but CSV and JSON requests did not use the same convention. Status aggregation logic assumes the start and end time naming convention and therefore did not work correctly for CSV and JSON requests. I modified the logic so that CSV and JSON requests use the start and end time naming pattern and verified this fixed status file aggregation in both cases.
The initial problem observed in ticket 12715 was caused by output directory collisions as addressed by changes for ticket 11983.
=> Issue #12715 - standardize status file naming

util/stream_dataset.py
Reverts oceanobservatories/stream_engine#35
Issue #13105 identified several streams which no longer could be downloaded and traced the problem back to this fix which needs to be revisited. In the meantime we are reverting this change so that data can be viewed/downloaded.
=> Revert "Issue #12879 Exclude data without a deployment"

RELEASE_NOTES.md, util/stream_dataset.py
As ticket states, caught this while working issue #12879.
Bug will currently only affect optaa since that's the only thing that has a custom dimension currently defined and also will only affect attempting to request unbounded data (which I'm not sure if this is possible for optaa, this is a special cause I ran into while forcing the data into a state where a deployment wasn't defined for it, to test work for #12879).
=> Issue #13195 Fix empty data error for custom dims

RELEASE_NOTES.md, config/default.py, engine/routes.py, util/releasenotes.py
- use release notes parser to determine version at runtime for output
to netcdf files
- add output to log on startup of the running stream engine version
=> Issue #13063 add release notes parser

RELEASE_NOTES.md, util/qc_executor.py
I did not update the release notes here as they already contain an entry for ticket 13276 and this is just a fix to that fix (which is not yet released to production). I think this solves the zombie issue we've been seeing. I did some local testing before and after the change and verified zombies occurred when I made a data request without the fix and do not occur when I make a request after the fix.
=> Issue #13276 - wait for child process

RELEASE_NOTES.md, test/test_aggregation.py, util/aggregation.py, util/datamodel.py, util/xarray_overrides.py
Added a patched version of _dataset_concat to xarray_overrides so that coordinates not present in all source NetCDF files for an aggregation are dropped (made non-coordinates, not removed entirely) instead of leading to a ValueError. Also corrected a bug in xarray's _dataset_concat where it failed to check the 1st dataset for consistency with the rest of the datasets for concatentation.
NOTE: The mentioned ValueError does not occur unless coordinates are decoded. When they are not decoded, the result is erroneous dropping of unrelated coordinates in the resulting Dataset.
=> Issue #13501 - remove unmatched coordinates during aggregation

RELEASE_NOTES.md, util/stream_dataset.py
This will allow stream engine to call a function even if an argument to the function was resolved but it did not contain any data. In this case the argument must be specified as optional in its preload definition and the function must provide a default value for that argument in its signature.
=> Issue #14518 Allow optional args during derived product function arg binding

RELEASE_NOTES.md, config/default.py, util/cass.py, util/metadata_service/partition.py, util/stream_dataset.py
In this change, for supporting (interpolated) streams (ie. not the primary requested stream), we will fetch from Cassandra 1 extra data point on both sides immediately outside of the requested time range for higher quality interpolation of supporting stream data into the primary data set at the request time boundaries. The extra data points must be within the time range of the deployments. Note that we only fetch 1 data point on each side since fetching more than this does not have any additional effect as the SciPy interpolate function we are using interpolates from a straight line (linear) drawn between the supporting stream's data points.
=> Issue #14387 pCO2 sensors not returning recent data

RELEASE_NOTES.md, util/stream_dataset.py
Do not interpolate raw data parameters (L0) from from the source dataset from one deployment into the target dataset for another deployment for that same instrument.
=> Issue #14573 - Dont interpolated raw data across deployments

RELEASE_NOTES.md, util/netcdf_generator.py
If an interpolated parameter has the same name as a parameter in the primary stream, there is a naming conflict error that prevents netcdf generation. The fix will check if a parameter name already exists in a dataset before trying to rename another parameter to that same name. If the name is already being used, the name of the interpolated parameter will not be changed and will appear in the dataset in the format "interpolated_stream_name-parameter_name".
=> Issue #14535 - Parameter naming conflict prevents netcdf generation

RELEASE_NOTES.md, conda_env.yml, requirements.txt, util/common.py, util/netcdf_generator.py, util/qartod_qc_executor.py
Implement some corrections/enhancements to QARTOD variable names and attributes:
-add QARTOD variables to the 'ancillary_variables' attribute of the parameter they describe
-add a 'references' attribute pointing to QARTOD documentation
-add a 'standard_name' attribute of the form "<parameter standard name> status_flag"
-add a 'comment' attributes with a brief description, and in the case of the "secondary flag", explaining the test result encoding
-update 'flag_meaning' attribute to be lowercase and use more descriptive names (in line with QARTOD manual flag naming)
-update 'long_name' attribute to the form "<parameter long name> <short descriptive phrase>"
-rename QARTOD variables to "qartod_results" and "qartod_executed" (these names are not necessarily final, but at least represent an …
=> Issue #14398 - Cleanup QARTOD NetCDF variables

RELEASE_NOTES.md, config/default.py, util/datamodel.py, util/stream_request.py
Streams using a collocated CTD for pressure (which gets added by existing logic in stream_engine) need to have stream_engine add the depth parameter from that same CTD stream. Other streams, e.g. CTD streams themselves, have depth added to them via preload-database updates.
=> Issue #14675 - Compute depth from pressure

scripts/load_qartod.py
Updating `scripts/load_qartod.py` to try to load Postgres credentials from environment variables.
The variables are:
* `POSTGRES_HOSTNAME`
* `POSTGRES_USERNAME`
* `POSTGRES_PASSWORD`
Use this with the new `qartod/load_all_csvs_into_postgres.sh` file added to the [qc-lookup](https://github.com/oceanobservatories/qc-lookup) repo to load qartod tests for all available CSVs by providing the above variables in a `.env` file alongside that script. This is to help avoid requiring a human in the loop to run `load_qartod.py` in a scripted environment.
=> FEAT: load_qartod.py -  read Postgres credentials from .env file

RELEASE_NOTES.md, config/default.py
Removed IFCB deduplciation map setting from default.py. Site-specific configs belong in configs/local.py.
=> Changing location of deduplication map setting
