engine/routes.py, util/calc.py
added support for limits on number of particles returned
=> add limit support

RELEASE_NOTES, util/asset_management.py
Change-Id: Iebf17c5a09b11e7f4ebbe18e9bcfdcdf6ef8253c
=> Issue #9306 - add depth lookup from asset management

manage-streamng
- source in the common ooi/engine miniconda environment when running this script
=> setup stream manager to use the ooi/engine env

RELEASE_NOTES, config/default.py
Update in preparation for tagging release for sprint8 deployment
=> Rjelkins patch 1

RELEASE_NOTES, util/netcdf_generator.py
Change-Id: I65a6e604bd91269b4b6c62d2ab655be9366e4d08
=> Issue #12318 - filter NetCDF parameters

manage-streamng
I primarily modified manage-streamng to run ok whether executed directly or via a soft link. I also made it use its NAME variable throughout the script.
=> Issue #12501 Modify for conda packaging

RELEASE_NOTES.md, util/netcdf_generator.py
- Add instrument and stream attribute for parameters from external streams
- Add ancillary_variables attribute to paramters derived from other values
=> Issue #12544 Add derived and external parameter attributes

RELEASE_NOTES.md, util/netcdf_generator.py, util/stream_request.py
- make sure that external parameters are included in the params to include list
- as a side affect this also fixes acceptance criteria 1 for Issue #12544
=> Issue #12886 - Fix missing external parameters

RELEASE_NOTES.md, config/default.py, util/aggregation.py, util/jsonresponse.py, util/netcdf_generator.py, util/netcdf_utils.py, util/stream_dataset.py
- add support for custom dimensional data sets
- add support for __builtin__ PythonFunction preload database functions
=>  Issue #13025 Add support for custom dimensional data sets

util/jsonresponse.py
- accidently introduced whitespace problem while editing code in vimdiff
=> Issue #13025 fix whitespace issue in jsonresponse.py

RELEASE_NOTES.md, config/default.py, test/test_stream_request.py, util/jsonresponse.py, util/netcdf_generator.py, util/stream_request.py
Issue #9328 Adding interpolated ctd pressure to NetCDF files
- add interpolated cdt pressure to the data request
- ensure interpolated ctd pressure is included in NetCdF
- modified unit tests to properly handle modified program logic
=>  Issue #9328 Adding interpolated ctd pressure to NetCDF files 

RELEASE_NOTES.md, util/stream_dataset.py
Backport 13195 fix into release 1.4
=> Issue #13195 - Fix empty datasets with custom dims not being handled correctly

RELEASE_NOTES.md, engine/routes.py, util/common.py
- This fix should also fix other errors that were always getting
returned under 500 code instead of a more appropriate code.
=> Issue #13153 - Fix return code for No Data to be 404 - Not Found

RELEASE_NOTES.md, test/test_annotations.py, test/test_stream_dataset.py, util/aggregation.py, util/annotation.py, util/calc.py, util/common.py, util/csvresponse.py, util/jsonresponse.py, util/netcdf_generator.py
=> Issue #13126 - Restore stream key data to annotation filenames

RELEASE_NOTES.md, util/csvresponse.py
Asynchronous download of specific parameters to CSV and NetCDF is inconsistent
=> Issue #13299 Implemented parameter filtering as part of CSV packaging

.travis.yml, conda_env.yml, config/default.py, engine/routes.py, requirements.txt, test/data/TEST_RELEASE_NOTES.md, test/test_releasenotes.py, util/releasenotes.py
TEST_RELEASE_NOTES.md is just a snapshot/copy of RELEASE_NOTES.md before my changes. That way I have a stable test file.
=> Issue #12816 - Add version endpoint with dependency info

RELEASE_NOTES.md, config/stream_nc_sizes.cfg
Apparently I need to update this file to list the new stream.
=> Issue #14304 Specify parameters for new METBK CT parser

README.md, RELEASE_NOTES.md, movecassdata.py, util/cass.py, util/common.py, util/datamodel.py, util/san.py
Some of these changes utilize the ooi-metadata-service-api changes recently merged. There's also uframe-ooi changes that are exercised by those changes that will be out for review.
=> Issue 14540: Provide way to correct refdes on particle data

scripts/load_qartod.py, util/qartod_qc_executor.py
re-instating changes that were removed in v1.19.2
=> Issue 15227 15266

config/default.py, util/aggregation.py, util/multi_concat.py
Updated aggregation routine to create more consistent file sizes.  Fixed OPTAA aggregation issue related to improper dimension sizes on non obs dimensions.
=> Issue 13624

util/stream_request.py
Fix issue where NetCDF files were missing data and QARTOD results for co-located CTDs
=> Issue #15486 

RELEASE_NOTES.md, util/qartod_qc_executor.py
Issue #15669 Add support for external parameters and improve error handling in QARTOD tests
=> Issue #15669 Add support for external parameters, improve error handling
